/* Local browser admin: all changes are stored in localStorage and instantly used by the storefront. */
document.addEventListener('DOMContentLoaded', () => {
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const KEYS = { products: 'vapeChnProducts', settings: 'vapeChnSettings', pin: 'vapeChnAdminPin' };
  const flavours = ['Arctic Berry', 'Citrus Mango', 'Grape Frost', 'Watermelon Mint', 'Blue Razz Ice', 'Peach Lychee', 'Kiwi Melon', 'Cherry Cola', 'Lemon Lime', 'Blackcurrant Ice', 'Tropical Punch', 'Strawberry Mint', 'Passionfruit Ice', 'Apple Peach', 'Berry Blast', 'Mango Guava', 'Raspberry Ice', 'Coconut Melon', 'Pineapple Citrus', 'Minty Grape'];
  const positions = ['0% 0%', '100% 0%', '0% 100%', '100% 100%'];
  const defaults = Array.from({ length: 100 }, (_, i) => { const type = ['disposable', 'pod', 'salt'][i % 3]; const flavour = flavours[i % flavours.length]; return { id: i + 1, type, flavour, name: `Vape CHN ${type === 'pod' ? 'Pulse Pod' : type === 'salt' ? 'Reserve Salt' : 'Aura'} · ${flavour}`, price: type === 'pod' ? 2499 : type === 'salt' ? 899 : 1899, position: positions[i % 4], image: '' }; });
  const saved = key => { try { return JSON.parse(localStorage.getItem(key)); } catch { return null; } };
  let products = saved(KEYS.products) || defaults;
  let settings = saved(KEYS.settings) || { storeName: 'Vape Shop Chennai', whatsapp: '919000000000', call: '+91 90000 00000' };
  const pin = () => localStorage.getItem(KEYS.pin) || '2026';
  const save = () => { localStorage.setItem(KEYS.products, JSON.stringify(products)); localStorage.setItem(KEYS.settings, JSON.stringify(settings)); $('#save-state').textContent = 'All changes saved'; setTimeout(() => $('#save-state').textContent = 'All changes saved', 600); };
  const signIn = () => { $('#login-screen').hidden = true; $('#admin-app').hidden = false; render(); };
  $('#login-form').addEventListener('submit', e => { e.preventDefault(); if ($('#admin-pin').value === pin()) signIn(); else $('.login-error').textContent = 'Incorrect PIN. Try again.'; });
  $('#logout').addEventListener('click', () => { $('#admin-app').hidden = true; $('#login-screen').hidden = false; $('#admin-pin').value = ''; });
  const showView = view => { $$('.view').forEach(el => el.classList.toggle('active', el.id === `${view}-view`)); $$('.side-link').forEach(el => el.classList.toggle('active', el.dataset.view === view)); $('#page-title').textContent = view === 'overview' ? 'Dashboard' : view === 'products' ? 'Product catalogue' : 'Store settings'; };
  $$('.side-link').forEach(button => button.addEventListener('click', () => showView(button.dataset.view))); $$('[data-go]').forEach(button => button.addEventListener('click', () => showView(button.dataset.go)));
  const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
  const render = (query = '') => { const matches = products.filter(item => `${item.name} ${item.flavour} ${item.type}`.toLowerCase().includes(query.toLowerCase())); $('#product-count').textContent = products.length; $('#stat-products').textContent = products.length; $('#stat-whatsapp').textContent = settings.whatsapp || 'Not set'; $('#product-admin-grid').innerHTML = matches.map(item => `<article class="admin-product"><div class="admin-product-image ${item.image ? 'custom' : ''}" style="--pos:${item.position};${item.image ? `--img:url('${item.image}')` : ''}"></div><div class="admin-product-info"><p>${escapeHtml(item.type)} · ${escapeHtml(item.flavour)}</p><h3>${escapeHtml(item.name)}</h3><b>₹${Number(item.price).toLocaleString('en-IN')}</b><div class="admin-product-actions"><button data-edit="${item.id}">Edit</button><button class="delete" data-delete="${item.id}">Delete</button></div></div></article>`).join(''); $$('.admin-product-actions [data-edit]').forEach(button => button.addEventListener('click', () => openProduct(products.find(item => item.id === Number(button.dataset.edit))))); $$('.admin-product-actions [data-delete]').forEach(button => button.addEventListener('click', () => { if (confirm('Delete this product?')) { products = products.filter(item => item.id !== Number(button.dataset.delete)); save(); render($('#product-search').value); } })); };
  $('#product-search').addEventListener('input', e => render(e.target.value));
  const dialog = $('#product-dialog'), form = $('#product-form');
  const openProduct = item => { $('#product-dialog-title').textContent = item ? 'Edit product' : 'Add product'; form.reset(); if (item) Object.entries(item).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value; }); dialog.showModal(); };
  $('#add-product').addEventListener('click', () => openProduct());
  form.addEventListener('submit', e => { e.preventDefault(); const payload = Object.fromEntries(new FormData(form)); const id = Number(payload.id) || Date.now(); const product = { ...payload, id, price: Number(payload.price), image: payload.image.trim(), position: payload.position || '0% 0%' }; const existing = products.findIndex(item => item.id === id); if (existing >= 0) products[existing] = product; else products.unshift(product); save(); dialog.close(); render($('#product-search').value); });
  $('#settings-form').addEventListener('submit', e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); if (!/^\d{8,15}$/.test(values.whatsapp)) return alert('Enter a valid WhatsApp number with country code, digits only.'); if (!/^\d{4,}$/.test(values.pin)) return alert('Use at least 4 digits for the admin PIN.'); settings = { storeName: values.storeName.trim(), whatsapp: values.whatsapp, call: values.call.trim() }; localStorage.setItem(KEYS.pin, values.pin); save(); alert('Business settings saved. The storefront will use them after refresh.'); });
  const settingsForm = $('#settings-form'); Object.entries({ ...settings, pin: pin() }).forEach(([key, value]) => { if (settingsForm.elements[key]) settingsForm.elements[key].value = value; });
});
